blank_issues_enabled: true
contact_links:
  - name: ğŸ“š Documentation
    url: https://nuke.build/docs/getting-started/philosophy.html
    about: Read our comprehensive documentation
  - name: ğŸš€ First-Class Support
    url: https://github.com/sponsors/matkoch?frequency=one-time&sponsor=matkoch
    about: Make a sponsorship to receive professional support
  - name: ğŸ’¬ Chat on Slack
    url: https://slofile.com/slack/nukebuildnet
    about: Get in touch with the whole community
  - name: ğŸ¦ Follow on Twitter
    url: https://twitter.com/nukebuildnet
    about: Stay informed about the latest greatness